name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt: ["6.8"]
        include:
          - os: ubuntu-latest
            arch: 'linux_gcc_64'
          - os: windows-latest
            arch: 'win64_msvc2022_64'
          - os: macos-latest
            arch: 'clang_64'

    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}-qt-${{ matrix.qt }}"

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt }}
        arch: ${{ matrix.arch }}
        archives: icu qtbase

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
